apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "cirros-clone-pvc"
  namespace: "kubevirt-demo"
  labels:
    app: Host-Assisted-Cloning
  annotations:
    k8s.io/CloneRequest: "source-ns/cirros-pvc"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
